{% set name = "kadi-apy" %}
{% set version = "0.47.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/iam-cms/kadi-apy/-/archive/v{{ version }}/kadi-apy-v{{ version }}.tar.gz
  sha256: 58e962b957aa37f045177b950b9ddcb757005ab21f516f250fa8dd4a000b9897

build:
  entry_points:
    - kadi-apy=kadi_apy.cli.main:kadi_apy
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=8.0.0,<9.0.0
    - jsonref >=1.1.0,<2.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - rdflib >=7.0.0,<8.0.0
    - niquests >=3.13.0,<4.0.0
    - xmlhelpy >=0.14.0,<0.15.0

test:
  imports:
    - kadi_apy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - kadi-apy --help

about:
  home: https://gitlab.com/iam-cms/kadi-apy
  summary: 'Python API wrapper for Kadi4Mat'
  description: |
    Kadi-APY is a library for use in tandem with Kadi4Mat. The REST-like API of
    Kadi4Mat makes it possible to programmatically interact with most of the
    resources that can be used through the web interface by sending suitable HTTP
    requests to the different endpoints the API provides.
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
