schema_version: 1

context:
  name: kadi-apy
  version: "0.50.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://gitlab.com/iam-cms/kadi-apy/-/archive/v${{ version }}/kadi-apy-v${{ version }}.tar.gz
  sha256: 107f7cb995b726b3d97ab622c433509eda1ebea67ec7eea8717928a976c8c234

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - kadi-apy=kadi_apy.cli.main:kadi_apy

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - click >=8.0.0,<9.0.0
    - jsonref >=1.1.0,<2.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - rdflib >=7.0.0,<8.0.0
    - niquests >=3.13.0,<4.0.0
    - xmlhelpy >=0.14.0,<0.15.0

tests:
  - python:
      imports:
        - kadi_apy
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - kadi-apy --help

about:
  summary: Python API wrapper for Kadi4Mat
  description: |
    Kadi-APY is a library for use in tandem with Kadi4Mat. The REST-like API of
    Kadi4Mat makes it possible to programmatically interact with most of the
    resources that can be used through the web interface by sending suitable HTTP
    requests to the different endpoints the API provides.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://gitlab.com/iam-cms/kadi-apy

extra:
  recipe-maintainers:
    - jan-janssen
